### ISSUE TITLE
nativescript Angular 4+ support

### ISSUE THREAD

**Issue by hackerunet** [sean-perkins/nativescript-opentok#47]
Hi there, I'm not sure if this works in angular 4+ nativescript mobile application, I'm always receiving an undefined Session error and not sure if this works on such versions. Can you please tell me if it could run in tns angular 4+?? thanks

**Comment by hackerunet** [comment]
I hit this error each time I try to use this:
JS: TypeError: Cannot read property 'Session' of undefined
Also 2 more devs reported me that this plugin is not working, maybe there is something missing in the documentation, this is the full error stack, I think something is missing in the component view, copy and paste of the view suggested in the documentation is not working.
```
Successfully synced application org.nativescript.reliqhealthpatient on device emulator-5554.
JS: ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'Session' of undefined
JS: TypeError: Cannot read property 'Session' of undefined
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.reliqhealthpatient/files/app/tns_modules/nativescript-opentok/src/android/session.js:5:34)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.reliqhealthpatient/files/app/tns_modules/nativescript-opentok/opentok.js:6:10)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.reliqhealthpatient/files/app/search/search.component.js:5:17)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.reliqhealthpatient/files/app/search/search-routing.module.js:5:26)
JS:     at require (<anonymous>:1:266)
JS:     at Object.<anonymous> (file:///data/data/org.nativescript.reliqhealthpatient/files/app/search/search.module.js:5:31)
JS:     at require (<anonymous>:1:266)
JS:     at file:///data/data/org.nativescript.reliqhealthpatient/files/app/tns_modules/tns-core-modules/globals/globals.js:92:32
JS:     at new ZoneAwarePromise (file:///data/data/org.nativescript.reliqhealthpatient/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
JS:     at Object.import (file:///data/data/org.nativescript.reliqhealthpatient/files/app/tns_modules/tns-core-modules/globals/globals.js:90:16)
JS:     at SystemJsNgModuleLoader.loadAndCompile (file:///data/data/org.nativescript.reliqhealthpatient/files/app/tns_modules/@angular/core/bundles/core.umd.js:6608:29)
JS:     at SystemJsNgModuleLoader.load (file:///data/data/org.nativescript.reliqhealthpatient/files/app/tns_modules/@angular/core/bundles/core.umd.js:6592:60)
^[[2~
```
In the building there are missing dependencies apparently, calling var Session = com.opentok.android.Session; is totally undefined, so do you think there could be a fix for this?

**Comment by hackerunet** [comment]
As no one attended this, I fix all issues by downgrading opentok sdk from last version to 2.15 editing maven and recompiling. so for those having Android issues like hanging or application crashing just do this.
